- hosts: localhost
  become: true
  pre_tasks:
    - name: Upgrade Arch
      community.general.pacman:
        update_cache: true
        upgrade: true
      tags:
        - arch
  tasks:
    - include: ansible-tasks/arch.yml
    - include: ansible-tasks/ubuntu.yml
    - name: Change default shell
      shell: chsh -s `which zsh`
      tags:
        - arch
    - name: 'Install oh-my-zsh'
      uri:
        url: 'https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh'
        method: GET
        follow_redirects: safe
      register: result

