- hosts: localhost
  become: true
  pre_tasks:
    - name: Upgrade Arch
      community.general.pacman:
        update_cache: true
        upgrade: true
      tags:
        - always
  tasks:
    - name: ZSH Tasks
      ansible.builtin.include_tasks:
        file: tasks/zsh.yml
        apply:
          tags:
            - zsh
      tags:
        - zsh
    - name: AUR Helper
      ansible.builtin.include_tasks:
        file: tasks/aur.yml
    - name: Terminal setup
      ansible.builtin.include_tasks:
        file: tasks/tui.yml
    - name: Hyprland setup
      ansible.builtin.include_tasks:
        file: tasks/gui.yml
# - tui:
  # - nvim
  # - tmux
  # - setup zsh
  #   - antigen
  # lazygit e lazydocker
  # - ssh keys e gpg
# - gui:
  # hyprland
