- name: Install git
  community.general.pacman:
    name: git
    state: present
- name: Ensure base-devel is installed
  community.general.pacman:
    name: base-devel
    state: present
- name: Install zoxide
  community.general.pacman:
    name: zoxide
    state: present
- name: Install eza
  community.general.pacman:
    name: eza
    state: present
- name: Install bob
  community.general.pacman:
    name: bob
    state: present
- name: Install neovim from bob
  ansible.builtin.shell: |
    /usr/bin/bob use stable
- name: Install docker
  community.general.pacman:
    name: docker
    state: present
- name: Install bat
  community.general.pacman:
    name: bat
    state: present
- name: Install lazygit
  community.general.pacman:
    name: lazygit
    state: present
- name: Install delta
  community.general.pacman:
    name: git-delta
    state: present
